version: '3'

services:
    db:
        image: postgres
        volumes:
            - db_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: {{ project_name }}
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: dbpw
    mc:
        image: memcached
    dj:
        build: .
        depends_on:
            - db
            - mc
        volumes:
            - media:/app/media
        environment:
            DEBUG: 0
            MAINTENANCE_MODE: 0
            CACHE_URL: pymemcache://mc:11211
            DATABASE_URL: psql://postgres:dbpw@db:5432/{{ project_name }}
    ws:
        build: nginx
        ports:
            - 0.0.0.0:8080:8080
        depends_on:
            - dj
        volumes:
            - ./nginx/:/etc/nginx/conf.d/
            - media:/usr/share/nginx/media

volumes:
    db_data:
    media:
