version: '3'

services:
    db:
        image: postgres
        volumes:
            - {{ project_name }}_db:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: {{ project_name }}
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: dbpw
    dj:
        build: .
        image: {{ project_name }}_dev
        volumes:
            - {{ project_name }}_media:/app/media
        depends_on:
            - db
        environment:
            DEBUG: 1
            DATABASE_URL: psql://postgres:dbpw@db:5432/{{ project_name }}
    lb:
        image: nginx
        ports:
            - 0.0.0.0:8080:8080
        volumes:
            - ./nginx/:/etc/nginx/conf.d/
            - {{ project_name }}_media:/srv/media
        depends_on:
            - dj
        environment:
          - NGINX_ENTRYPOINT_QUIET_LOGS=1

volumes:
    {{ project_name }}_db:
    {{ project_name }}_media:
